# name: Pep8

# on:
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         ref: ${{ github.event.pull_request.head.sha }} # Check only last commit
#     - name: 'Run PEP8'
#       uses: quentinguidee/pep8-action@v1
#       with:
#         arguments: '--max-line-length=120'

name: Pep8

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
    - name: Analysing the code with pycodestyle
      run: |
        pycodestyle --max-line-length=120 --show-source $(git ls-files '*.py')
